baseURL: https://keepearthcool.info
languageCode: en-us
defaultContentLanguage: en
title: KeepEarthCool.info
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Learn about climate change, and what you can do to help
  homeMetaContent: Learn about climate change, and what you can do to help
  footer: \"Keep Earth Cool\" graphic by Golnaz Eghtesad. Website made with contributions from Ayman Baydoun, Golnaz Eghtesad, Isabella Ramirez, Willow Ramsay, and Erica Stevenson
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: What is Climate Change?
      url: /what_is_climate_change
      weight: 2
    - name: How Does it Work?
      url: /how_does_it_work
      weight: 3
    - name: Why is it Happening?
      url: /why_is_it_happening
      weight: 4
    - name: Why Should I Care?
      url: /why_care
      weight: 5
    - name: Climate Change In The News
      url: /in_the_news
      weight: 6
    - name: Emissions In The US
      url: /emissions_in_us
      weight: 7
    - name: Emissions In The US
      url: /emissions_in_us
      weight: 8
    - name: What Can Be Done?
      url: /what_can_be_done
      weight: 9
    - name: Climate Change In Pictures
      url: /in_pictures
      weight: 10
    - name: Weather in the 21st Century
      url: /weather
      weight: 10
    # - name: RSS
    #   url: /index.xml
    #   weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
